version: '3'

services:

  mleap1:
    image: 192.168.2.150/zrar/mleap-serving:0.9.0-SNAPSHOT
    restart: unless-stopped
    volumes:
      - /opt/models:/models
    networks:
      - my-bridge

  mleap2:
    image: 192.168.2.150/zrar/mleap-serving:0.9.0-SNAPSHOT
    restart: unless-stopped
    volumes:
      - /opt/models:/models
    networks:
      - my-bridge

  mleap3:
    image: 192.168.2.150/zrar/mleap-serving:0.9.0-SNAPSHOT
    restart: unless-stopped
    volumes:
      - /opt/models:/models
    networks:
      - my-bridge

  mleap4:
    image: 192.168.2.150/zrar/mleap-serving:0.9.0-SNAPSHOT
    restart: unless-stopped
    volumes:
    - /opt/models:/models
    networks:
    - my-bridge

  mleap5:
    image: 192.168.2.150/zrar/mleap-serving:0.9.0-SNAPSHOT
    restart: unless-stopped
    volumes:
    - /opt/models:/models
    networks:
    - my-bridge

  mleap-controller:
    image: 192.168.2.150/zrar/mleap-controller:1.0.4
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - /opt/models:/models
    networks:
      - my-bridge

networks:
  my-bridge:
    driver: bridge